name: Laravel CI - testing

on:
  push:
    branches:
      - develop
env:
  ONLINE_DOCKER_IMAGE: ${{ secrets.ONLINE_DOCKER_IMAGE }}
  PROJECT_ENV_KEY: ${{ secrets.PROJECT_ENV_KEY }}

jobs:
  laravel-ci:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Actions checkout
        uses: actions/checkout@v2
      - name: Copy .env
        run: |
          composer install
          php artisan env:decrypt --key=${{ secrets.PROJECT_ENV_KEY }} --env=testing --force
          cp .env.testing .env
          rm -rf vendor
      - name: Build the stack
        run: |
          docker-compose up -d
      - name: Execute tests via PHPUnit
        run: |
          docker-compose exec -T chat composer install
          docker-compose exec -T chat php artisan config:cache
          docker-compose exec -T chat php artisan test
